version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Build Amir
          command: docker build -t $DOCKER_USER/$CONTAINER:$VERSION --build-arg version=$VERSION .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS 
      - run:
          name: Docker push
          command: docker push $DOCKER_USER/$CONTAINER

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: run sh
          command: chmod +x ./deploy.sh && ./deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build 
      - deploy:
          requires:
            - build